### ISSUE TITLE
Simplify init config & implement loading of bootstrap information from seed file

### ISSUE THREAD

**Issue by jdeepee** [perspect3vism/ad4m-executor#38]
## Tasks

- [x] Remove appDefaultLangPath
- [ ] <s>Remove ad4mBootstrapFixtures</s>
- [x] Remove ad4mBootstrapLanguages
- [x] Remove appBuiltInLangs
- [x] Add networkBootstrapSeed which contains path to bootstrap file
- [ ] load bootstrap information from seed file

## Schema of seed file:

```
{
    trustedAgents: ['did:key:zQ3shkkuZLvqeFgHdgZgFMUx8VGkgVWsLA83w2oekhZxoCW2n'],
    knownLinkLanguageTemplates: ['QmfDoeJgiG5Hs4DJcwPqDWbwU2Ks8zLSJjv7bR8is84Qt5'],
    directMessageLanguageTemplate: 'QmRENn31FvsZZx99tg8nd8oM52MmGYa1tLUYaDvYdjnJsb',
    
    agentLanguage: 'Qm2343245',
    perspectiveLanguage: 'Qm23r432wr4',
    neighbourhoodLanguage: 'Qm234234423',
    
    languageLanguageBundle: 'export function create(languageContext) {....}',
}
```
